#!/usr/bin/env python3
"""Generates the Lucent logo and Android launcher icons from one geometry.

Run from the repo root:  python3 tool/make_icon.py
Needs rsvg-convert (librsvg2-bin). Writes assets/brand/* and android res files.
"""
import os
import subprocess

# Faceted crystal in the 108x108 adaptive-icon grid (safe zone: r=33 around 54,54).
P = dict(T=(54, 23), UR=(74, 39), LR=(71, 67), B=(53, 86), LL=(35, 68), UL=(36, 37),
         C=(51, 50), D=(59, 64))
BG = '#14131C'
# (points, flat colour, alpha for the monochrome layer)
FACETS = [
    ('T UR C', '#B4C2FF', 1.00),
    ('T C UL', '#8A9CFF', 0.85),
    ('C UR LR D', '#6A7BF2', 0.70),
    ('UL C LL', '#5360E0', 0.60),
    ('LL C D B', '#3D3FB8', 0.45),
    ('D LR B', '#2B2A8C', 0.32),
]
OUTLINE = 'T UR LR B LL UL'


def pts(names):
    return [P[n] for n in names.split()]


def svg_points(names):
    return ' '.join(f'{x},{y}' for x, y in pts(names))


def path_data(names):
    p = pts(names)
    return 'M' + ' L'.join(f'{x},{y}' for x, y in p) + ' Z'


def crystal_svg():
    out = [f'<polygon points="{svg_points(OUTLINE)}" fill="#2B2A8C"/>']
    for names, col, _ in FACETS:
        out.append(f'<polygon points="{svg_points(names)}" fill="{col}" stroke="{col}" '
                   'stroke-width="0.3" stroke-linejoin="round"/>')
    return '\n  '.join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)


def render(svg, png, size):
    os.makedirs(os.path.dirname(png), exist_ok=True)
    subprocess.run(['rsvg-convert', '-w', str(size), '-h', str(size), svg, '-o', png], check=True)


# Full logo: rounded dark tile with the crystal (also used as the legacy icon).
logo = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="9 9 90 90">
  <rect x="9" y="9" width="90" height="90" rx="20" fill="{BG}"/>
  {crystal_svg()}
</svg>
'''
write('assets/brand/logo.svg', logo)
render('assets/brand/logo.svg', 'assets/brand/logo-1024.png', 1024)
render('assets/brand/logo.svg', 'assets/brand/logo-256.png', 256)

# Adaptive foreground only (transparent, full 108 grid) for previews.
fg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="432" height="432" viewBox="0 0 108 108">
  {crystal_svg()}
</svg>
'''
write('build/icon/foreground.svg', fg)
render('build/icon/foreground.svg', 'build/icon/foreground.png', 1080)

res = 'android/app/src/main/res'
for d, px in dict(mdpi=48, hdpi=72, xhdpi=96, xxhdpi=144, xxxhdpi=192).items():
    render('assets/brand/logo.svg', f'{res}/mipmap-{d}/ic_launcher.png', px)


def vector(body, comment):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by tool/make_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{body}
</vector>
'''


fg_paths = [f'    <path android:fillColor="#2B2A8C" android:pathData="{path_data(OUTLINE)}" />']
mono_paths = []
for names, col, alpha in FACETS:
    fg_paths.append(f'    <path android:fillColor="{col}" android:strokeColor="{col}" '
                    f'android:strokeWidth="0.3" android:strokeLineJoin="round" '
                    f'android:pathData="{path_data(names)}" />')
    mono_paths.append(f'    <path android:fillColor="#FFFFFF" android:fillAlpha="{alpha}" '
                      f'android:pathData="{path_data(names)}" />')
write(f'{res}/drawable/ic_launcher_foreground.xml',
      vector('\n'.join(fg_paths), 'Lucent crystal, flat facets, inside the adaptive safe zone.'))
write(f'{res}/drawable/ic_launcher_monochrome.xml',
      vector('\n'.join(mono_paths), 'Single-colour crystal for themed icons (facets by opacity).'))
write(f'{res}/values/ic_launcher_background.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{BG}</color>
</resources>
''')
write(f'{res}/mipmap-anydpi-v26/ic_launcher.xml', '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
''')
print('ok')
