#!/usr/bin/env python3
"""Generate Lucent icons from assets/brand/logo-source.png.

Run: python3 tool/make_icon.py (requires Pillow).
Full-colour icons preserve the original artwork and its pale background.
"""
import base64
from pathlib import Path
import shutil
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / 'assets/brand'
RES = ROOT / 'android/app/src/main/res'
SOURCE = BRAND / 'logo-source.png'
BG = '#FAFAF6'
DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}
OUTER = [(512,132), (769,358), (769,623), (512,808), (255,623), (255,358)]
INNER = [(512,334), (594,422), (558,495), (512,526), (466,495), (430,422)]


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def save(image, path, size):
    path.parent.mkdir(parents=True, exist_ok=True)
    image.resize((size, size), Image.Resampling.LANCZOS).save(path)


def main():
    with Image.open(SOURCE) as original:
        if original.size != (1024, 1024):
            raise ValueError('Expected 1024×1024 source artwork')
        image = original.convert('RGBA')
    shutil.copyfile(SOURCE, BRAND / 'logo-1024.png')
    save(image, BRAND / 'logo-256.png', 256)
    data = base64.b64encode(SOURCE.read_bytes()).decode('ascii')
    write(BRAND / 'logo.svg', '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">\n'
          f'<image width="1024" height="1024" href="data:image/png;base64,{data}"/>\n</svg>\n')
    # 86dp artwork on a 108dp canvas keeps the gem within adaptive safe bounds.
    foreground = Image.new('RGBA', (1080, 1080), BG)
    foreground.paste(image.resize((860, 860), Image.Resampling.LANCZOS), (110, 110))
    for density, scale in DENSITIES.items():
        save(image, RES / f'mipmap-{density}/ic_launcher.png', round(48 * scale))
        save(foreground, RES / f'drawable-{density}/ic_launcher_artwork.png', round(108 * scale))
    write(RES / 'drawable/ic_launcher_foreground.xml', '''<?xml version="1.0" encoding="utf-8"?>
<!-- Original artwork, generated by tool/make_icon.py. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:width="108dp" android:height="108dp" android:gravity="center">
        <bitmap android:src="@drawable/ic_launcher_artwork" android:gravity="fill" />
    </item>
</layer-list>
''')
    write(RES / 'values/ic_launcher_background.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{BG}</color>
</resources>
''')
    # Themed icons require a single-colour silhouette, traced from the artwork.
    path = ' '.join('M' + ' L'.join(f'{x},{y}' for x,y in points) + ' Z' for points in (OUTER, INNER))
    write(RES / 'drawable/ic_launcher_monochrome.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Themed silhouette, generated by tool/make_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <group android:translateX="11" android:translateY="11"
        android:scaleX="0.083984375" android:scaleY="0.083984375">
        <path android:fillColor="#FFFFFF" android:fillType="evenOdd" android:pathData="{path}" />
    </group>
</vector>
''')
    write(BRAND / 'crystal.svg', '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">\n'
          f'<path d="{path}" fill="#B7BDC5" fill-rule="evenodd"/>\n</svg>\n')
    mask = Image.new('RGBA', (1024, 1024))
    draw = ImageDraw.Draw(mask)
    draw.polygon(OUTER, fill='#B7BDC5')
    draw.polygon(INNER, fill=(0,0,0,0))
    mask.save(BRAND / 'crystal-1024.png')
    save(foreground, ROOT / 'build/icon/foreground.png', 1080)
    mac = ROOT / 'macos/Runner/Assets.xcassets/AppIcon.appiconset'
    if mac.is_dir():
        tile = Image.new('RGBA', (1024, 1024))
        tile.paste(image.resize((824,824), Image.Resampling.LANCZOS), (100,100))
        for size in (16,32,64,128,256,512,1024):
            save(tile, mac / f'app_icon_{size}.png', size)
    print('Generated logos and launcher icons from the original artwork.')


if __name__ == '__main__':
    main()
